// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uevnoypnosbedjxrhpqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVldm5veXBub3NiZWRqeHJocHF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTY3MTAsImV4cCI6MjA2MDgzMjcxMH0.vV_R5jxOVzkjACihJPmRfeHQficKNHEsA34vxjhV7I8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);